In [1]:
source(file.path(Sys.getenv("CODEBASE"),"DNAmeth500species/src/00.0_init.R"))

Warning message:
“package ‘ggrepel’ was built under R version 3.6.3”
Warning message:
“package ‘ggseqlogo’ was built under R version 3.6.3”
Warning message:
“package ‘pheatmap’ was built under R version 3.6.3”
Joining, by = "species"

In [2]:
genome_dir = "../../resources/reference_genomes/"

In [4]:
genomes_df <- fread("/binfl/lv71484/droman/DNAmeth500species/results_analysis/validation/02_insilico_digest/genomes_to_run.tsv")

In [5]:
head(genomes_df)

  V1      V2           V3           V4                      V5
1 vicPac2 Alpaca       NA           NA                      Mammalia
2 dasNov3 Armadillo    NA           NA                      Malacostraca
3 gasAcu1 Stickleback  NA           NA                      Actinopteri
4 anoCar2 Lizard       Lizard       Anolis carolinensis     Reptilia
5 melUnd1 Budgerigar   Budgeriger   Melopsittacus undulatus Aves
6 aquChr2 Golden eagle Golden eagle Aquila chrysaetos       Aves

In [13]:
genomes_df

   V1            V2                       V3
1  vicPac2       Alpaca                   NA
2  dasNov3       Armadillo                NA
3  gasAcu1       Stickleback              NA
4  anoCar2       Lizard                   Lizard
5  melUnd1       Budgerigar               Budgeriger
6  aquChr2       Golden eagle             Golden eagle
7  chrPic1       Painted turtle           Painted turtle
8  calJac4       Marmoset                 NA
9  choHof1       Sloth                    NA
10 saiBol1       Squirrel monkey          Squirrel monkey
11 pteVam1       Megabat                  Megabat
12 aptMan1       Brown kiwi               NA
13 dipOrd1       Kangaroo rat             NA
14 oviAri4       Sheep                    Sheep
15 allMis1       American alligator       American alligator
16 canFam5       Dog                      NA
17 felCat9       Cat                      Cat
18 susScr11      Pig                      Pig
19 thaSir1       Garter snake             Garter snake
20 musFur1       Ferret                   Ferret
21 calMil1       Elephant shark           Elephant shark
22 equCab3       Horse                    NA
23 speTri2       Squirrel                 Squirrel
24 oryCun2       Rabbit                   Rabbit
25 cavPor3       Guinea pig               NA
26 tupBel1       Tree shrew               Tree shrew
27 taeGut2       Zebra finch              Zebra finch
28 myoLuc2       Microbat                 Microbat
29 mm39          Mouse                    NA
30 nanPar1       Tibetan frog             Tibetan frog
⋮  ⋮             ⋮                        ⋮
48 oreNil2       Nile tilapia             Nile tilapia
49 danRer11      Zebrafish                Zebrafish
50 petMar3       Lamprey                  NA
51 fr3           Fugu                     Fugu
52 tetNig2       Tetraodon                NA
53 geoFor1       Medium ground finch      Medium ground finch
54 melGal5       Turkey                   NA
55 triMan1       Manatee                  NA
56 proCap1       Rock hyrax               NA
57 echTel2       Tenrec                   NA
58 macFas5       Crab-eating macaque      NA
59 chlSab2       Green Monkey             Green Monkey
60 rheMac10      Rhesus                   Rhesus
61 xenLae2       African clawed frog      African clawed frog
62 xenTro9       X. tropicalis            Tropical clawed frog
63 rhiRox1       Golden snub-nosed monkey NA
64 nasLar1       Proboscis Monkey         NA
65 hg38          Human                    Human
66 braFlo1       Lancelet                 Lancelet
67 aplCal1       Sea Hare                 Sea Hare
68 latCha1       Coelacanth               Coelacanth
69 sarHar1       Tasmanian devil          Tasmanian devil
70 monDom5       Opossum                  Opossum
71 nomLeu3       Gibbon                   Gibbon
72 gorGor6       Gorilla                  Gorilla
73 panTro6       Chimp                    Chimp
74 panPan2       Bonobo                   Bonobo
75 sorAra2       Shrew                    Shrew
76 macEug2       Wallaby                  Wallaby
77 AmexG_v6.0-DD Axolotl                  Axolotl
   V4                              V5
1  NA                              Mammalia
2  NA                              Malacostraca
3  NA                              Actinopteri
4  Anolis carolinensis             Reptilia
5  Melopsittacus undulatus         Aves
6  Aquila chrysaetos               Aves
7  Chrysemys picta                 Reptilia
8  NA                              Mammalia
9  NA                              Mammalia
10 Saimiri boliviensis boliviensis Mammalia
11 Pteropus vampyrus               Mammalia
12 NA                              Aves
13 NA                              Mammalia
14 Ovis aries                      Mammalia
15 Alligator mississippiensis      Reptilia
16 NA                              Mammalia
17 Felis catus                     Mammalia
18 Sus scrofa                      Mammalia
19 Thamnophis sirtalis             Reptilia
20 Mustela putorius furo           Mammalia
21 Callorhinchus milii             Chondrichthyes
22 NA                              Mammalia
23 Ictidomys tridecemlineatus      Mammalia
24 Oryctolagus cuniculus           Mammalia
25 NA                              Mammalia
26 Tupaia belangeri                Mammalia
27 Taeniopygia guttata             Aves
28 Myotis lucifugus                Mammalia
29 NA                              Mammalia
30 Nanorana parkeri                Amphibia
⋮  ⋮                               ⋮
48 Oreochromis niloticus           Actinopteri
49 Danio rerio                     Actinopteri
50 NA                              Hyperoartia
51 Takifugu rubripes               Actinopteri
52 NA                              Actinopteri
53 Geospiza fortis                 Aves
54 NA                              Aves
55 NA                              Mammalia
56 NA                              Mammalia
57 NA                              Mammalia
58 NA                              Mammalia
59 Chlorocebus sabaeus             Mammalia
60 Macaca mulatta                  Mammalia
61 Xenopus laevis                  Amphibia
62 Xenopus tropicalis              Amphibia
63 NA                              Mammalia
64 NA                              Mammalia
65 Homo sapiens                    Mammalia
66 Cephalochordata                 Invertebrata
67 Aplysia californica             Invertebrata
68 Latimeria chalumnae             Actinopteri
69 Sarcophilus harrisii            Marsupiala
70 Monodelphis domestica           Marsupiala
71 Nomascus leucogenys             Mammalia
72 Gorilla gorilla                 Mammalia
73 Pan troglodytes                 Mammalia
74 Pan paniscus                    Mammalia
75 Sorex araneus                   Mammalia
76 Notamacropus eugenii            Marsupiala
77 Ambystoma mexicanum             Amphibia

In [8]:
genomes_df <-rbind(genomes_df,list("AmexG_v6.0-DD", "Axolotl","Axolotl", "Ambystoma mexicanum", "Amphibia"))

In [26]:
latin_names <- list("vicPac2" = "Vicugna pacos", "dasNov3" = "Dasypus novemcinctus", "gasAcu1" = "Gasterosteus aculeatus", "calJac4" = "Callithrix jacchus", "choHof1" = "Choloepus hoffmanni",
"aptMan1" = "Apteryx australis", "dipOrd1" = "Dipodomys ordii", "canFam5" = "Canis lupus familiaris", "equCab3" = "Equus caballus", "cavPor3" = "Cavia porcellus", "mm39" = "Mus musculus",
"loxAfr3" = " Loxodonta africana", "neoSch1" = "Monachus schauinslandi", "eriEur2" = "Erinaceus europaeus", "bisBis1" = "Bison bison bison", "criGri1" = "Cricetulus griseus",
"micMur2" = "Microcebus murinus", "rn7" = "Rattus norvegicus", "papAnu4" = "Papio anubis", "strPur2" = "Strongylocentrotus purpuratus", "ci3" = "C. intestinalis",
"oryLat2" = "Oryzias latipes", "petMar3" = "Petromyzon marinus", "tetNig2" = "Tetraodon nigroviridis", "melGal5" = "Meleagris gallopavo","triMan1" = " Trichechus manatus latirostris",
"proCap1" = "Procavia capensis", "echTel2" = "Echinops telfairi", "macFas5" = "Macaca fascicularis",  "rhiRox1" = "Rhinopithecus roxellana", "nasLar1" = "Nasalis larvatus")

In [30]:
genomes_df[is.na(V4)]$V4 <- as.character(latin_names[genomes_df[is.na(V4)]$V1])

In [39]:
genome_summary = data.table()

In [40]:
for(i in seq_along(genomes_df$V1)){
    
genome_id <- genomes_df[i,]$V1

kmer01 <- as.data.frame(t(read.csv(file.path(genome_dir, genome_id,"kmer01"), row.names = 1, sep = " ")))["order",]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
kmer01$genome <- genome_id

kmer02 <- as.data.frame(t(read.csv(file.path(genome_dir, genome_id,"kmer02"), row.names = 1, sep = " "))["order",c("CG"), drop = FALSE])
kmer02$genome <- genome_id

kmer <- full_join(kmer01, kmer02)

kmer$CG_OE <- kmer$CG/(kmer$C*kmer$G)
kmer$CG_freq <- kmer$C + kmer$G

genome_size <- fread(file.path(genome_dir,genome_id, paste0(genome_id, ".chrom.sizes")))

kmer$total_bp <- sum(genome_size$V2)
kmer$N_chr <- NROW(genome_size)

annot_files <- list.files(file.path(genome_dir, genome_id, "tracks"))
repeat_file <- file.path(genome_dir, genome_id, "tracks", paste0(genome_id, "_rmsk.bed"))
if(!file.exists(repeat_file)){
    repeat_file <- file.path(genome_dir, genome_id, "tracks", paste0(genome_id, "_simpleRepeat.bed"))
    if(!file.exists(repeat_file)){
        
        read_repeat_flag <- FALSE
    }else{
        read_repeat_flag <- TRUE
    }
}else read_repeat_flag <- TRUE
       
if(read_repeat_flag){
    repeats <- fread(repeat_file)

repeats[, width:= V3-V2, ]

kmer$repeats_ratio <- sum(repeats$width)/kmer$total_bp
}else kmer$repeats_ratio <- NA



ref_file <- annot_files[grepl("ref", tolower(annot_files))]

gene_annot <- fread(file.path(genome_dir, genome_id, "tracks",ref_file))

kmer$n_genes_annotated <- NROW(gene_annot)

kmer$gene_annotation <- gsub(paste0(genome_id, "_"), "", gsub(".bed", "", ref_file))
   kmer$common_name <- genomes_df[i,]$V2
kmer$latin_name <- genomes_df[i,]$V4 
genome_summary <- rbind(kmer, genome_summary)


}

Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 15 columns (i.e. invalid file). Added 14 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”
Warning message in fread(file.path(genome_dir, genome_id, "tracks", ref_file)):
“Detected 1 column names but the data has 12 columns (i.e. invalid file). Added 11 extra default column names at the end.”
Joining, by = "genome"

Warning message in fread(repeat_file):
“Detected 1 column names but the data has 6 columns (i.e. invalid file). Added 5 extra default column names at the end.”

In [41]:
head(genome_summary)

  A      C      G      T      genome        CG       CG_OE     CG_freq
1 0.2700 0.2300 0.2300 0.2700 AmexG_v6.0-DD 0.024830 0.4693762 0.4600
2 0.3056 0.1942 0.1940 0.3062 macEug2       0.005004 0.1328209 0.3882
3 0.2856 0.2145 0.2144 0.2855 sorAra2       0.014470 0.3146418 0.4289
4 0.2960 0.2037 0.2038 0.2965 panPan2       0.009519 0.2292958 0.4075
5 0.2962 0.2035 0.2036 0.2967 panTro6       0.010300 0.2485965 0.4071
6 0.2966 0.2032 0.2032 0.2969 gorGor6       0.010460 0.2533286 0.4064
  total_bp    N_chr  repeats_ratio n_genes_annotated gene_annotation
1 26730690244     28        NA     1977265           AmexT_v47-refGenes.gtf
2  3075184024 277711 0.3933385      598021           xenoRefGene
3  2423158183  12845 0.2974883       23525           refSeqComposite
4  3286643896  10274 0.4209457       59345           refSeqComposite
5  3050398082   4346 0.5296771      102471           refSeqComposite
6  3044872214   5486 0.4955004       61950           refSeqComposite
  common_name latin_name
1 Axolotl     Ambystoma mexicanum
2 Wallaby     Notamacropus eugenii
3 Shrew       Sorex araneus
4 Bonobo      Pan paniscus
5 Chimp       Pan troglodytes
6 Gorilla     Gorilla gorilla

In [44]:
head(genome_summary[,c(14, 15, 5, 9, 10, 1:4, 6:8, 11)])

  common_name latin_name           genome        total_bp    N_chr  A
1 Axolotl     Ambystoma mexicanum  AmexG_v6.0-DD 26730690244     28 0.2700
2 Wallaby     Notamacropus eugenii macEug2        3075184024 277711 0.3056
3 Shrew       Sorex araneus        sorAra2        2423158183  12845 0.2856
4 Bonobo      Pan paniscus         panPan2        3286643896  10274 0.2960
5 Chimp       Pan troglodytes      panTro6        3050398082   4346 0.2962
6 Gorilla     Gorilla gorilla      gorGor6        3044872214   5486 0.2966
  C      G      T      CG       CG_OE     CG_freq repeats_ratio
1 0.2300 0.2300 0.2700 0.024830 0.4693762 0.4600         NA
2 0.1942 0.1940 0.3062 0.005004 0.1328209 0.3882  0.3933385
3 0.2145 0.2144 0.2855 0.014470 0.3146418 0.4289  0.2974883
4 0.2037 0.2038 0.2965 0.009519 0.2292958 0.4075  0.4209457
5 0.2035 0.2036 0.2967 0.010300 0.2485965 0.4071  0.5296771
6 0.2032 0.2032 0.2969 0.010460 0.2533286 0.4064  0.4955004

In [45]:
my_wt(genome_summary[,c(14, 15, 5, 9, 10, 1:4, 6:8, 11)], file.path(analysis_dir, "validation", "genome_stats.tsv"))

In [46]:
genome_summary <- fread(file.path(analysis_dir, "validation", "genome_stats.tsv"))

In [47]:
head(genome_summary)

  common_name     latin_name                    genome  total_bp   N_chr  A
1 Sea Hare        Aplysia californica           aplCal1  715806041   8767 0.300
2 Lancelet        Cephalochordata               braFlo1  926386587      2 0.294
3 C. intestinalis C. intestinalis               ci3      115227500   1272 0.322
4 S. purpuratus   Strongylocentrotus purpuratus strPur2  907085737 114223 0.315
5 Elephant shark  Callorhinchus milii           calMil1  974498586  21204 0.288
6 Coelacanth      Latimeria chalumnae           latCha1 2860591921  22819 0.294
  C     G     T     CG    CG_OE CG_freq repeats_ratio class
1 0.201 0.201 0.299 0.025 0.627 0.402   0.083         Invertebrata
2 0.206 0.206 0.294 0.028 0.663 0.412   0.063         Invertebrata
3 0.178 0.178 0.322 0.028 0.867 0.357   0.149         Invertebrata
4 0.185 0.185 0.315 0.023 0.676 0.370   0.129         Invertebrata
5 0.212 0.212 0.288 0.020 0.445 0.423   0.271         Chondrichthyes
6 0.206 0.206 0.294 0.012 0.277 0.412   0.071         Actinopteri
  download_link
1 http://hgdownload.soe.ucsc.edu/goldenPath/aplCal1/bigZips/aplCal1.fa.gz
2 http://hgdownload.soe.ucsc.edu/goldenPath/braFlo1/bigZips/braFlo1.fa.gz
3 http://hgdownload.soe.ucsc.edu/goldenPath/ci3/bigZips/ci3.fa.gz
4 http://hgdownload.soe.ucsc.edu/goldenPath/strPur2/bigZips/strPur2.fa.gz
5 http://hgdownload.soe.ucsc.edu/goldenPath/calMil1/bigZips/calMil1.fa.gz
6 http://hgdownload.soe.ucsc.edu/goldenPath/latCha1/bigZips/latCha1.fa.gz

In [47]:
genome_summary <- left_join(genome_summary, genomes_df[, c("V1", "V5")], by = c("genome" ="V1"))

In [50]:
head(genome_summary)

  common_name latin_name           genome        total_bp    N_chr  A
1 Axolotl     Ambystoma mexicanum  AmexG_v6.0-DD 26730690244     28 0.2700
2 Wallaby     Notamacropus eugenii macEug2        3075184024 277711 0.3056
3 Shrew       Sorex araneus        sorAra2        2423158183  12845 0.2856
4 Bonobo      Pan paniscus         panPan2        3286643896  10274 0.2960
5 Chimp       Pan troglodytes      panTro6        3050398082   4346 0.2962
6 Gorilla     Gorilla gorilla      gorGor6        3044872214   5486 0.2966
  C      G      T      CG       CG_OE     CG_freq repeats_ratio V5
1 0.2300 0.2300 0.2700 0.024830 0.4693762 0.4600         NA     Amphibia
2 0.1942 0.1940 0.3062 0.005004 0.1328209 0.3882  0.3933385     Marsupiala
3 0.2145 0.2144 0.2855 0.014470 0.3146418 0.4289  0.2974883     Mammalia
4 0.2037 0.2038 0.2965 0.009519 0.2292958 0.4075  0.4209457     Mammalia
5 0.2035 0.2036 0.2967 0.010300 0.2485965 0.4071  0.5296771     Mammalia
6 0.2032 0.2032 0.2969 0.010460 0.2533286 0.4064  0.4955004     Mammalia

In [49]:
unique(genome_summary$V5)

 [1] "Amphibia"       "Marsupiala"     "Mammalia"       "Actinopteri"
 [5] "Invertebrata"   "Aves"           "Hyperoartia"    "Ascidiacea"
 [9] "Echinoidea"     "Chondrichthyes" "Reptilia"       "Malacostraca"

In [51]:
colnames(genome_summary)[14] <- "class"

In [52]:
genome_summary[class == "Hyperoartia",class := "Jawless vertebrate",  ]

In [53]:
class_colors

      Invertebrata Jawless_vertebrate     Chondrichthyes        Actinopteri
         "#cfcfcf"          "#636363"          "#F68383"          "#EA4142"
          Amphibia           Reptilia               Aves        Marsupialia
         "#5AB349"          "#8761AC"          "#FE9222"          "#8EBFDA"
          Mammalia
         "#4892C2"

In [54]:
genome_summary[class %in% c("Echinoidea","Ascidiacea"), class := "Invertebrata",]

In [55]:
genome_summary[class == "Malacostraca",class := "Mammalia",  ]

In [56]:
genome_summary[class == "Marsupiala",class := "Marsupialia",  ]

In [57]:
genome_summary$class <- factor(genome_summary$class, levels = names(class_colors))

In [65]:
head(genome_summary)

  common_name     latin_name                    genome  total_bp   N_chr
1 Sea Hare        Aplysia californica           aplCal1  715806041   8767
2 Lancelet        Cephalochordata               braFlo1  926386587      2
3 C. intestinalis C. intestinalis               ci3      115227500   1272
4 S. purpuratus   Strongylocentrotus purpuratus strPur2  907085737 114223
5 Elephant shark  Callorhinchus milii           calMil1  974498586  21204
6 Coelacanth      Latimeria chalumnae           latCha1 2860591921  22819
  A      C      G      T      CG    CG_OE CG_freq repeats_ratio class
1 0.2995 0.2008 0.2007 0.2991 0.025 0.627 0.402   0.083         Invertebrata
2 0.2941 0.2059 0.2059 0.2942 0.028 0.663 0.412   0.063         Invertebrata
3 0.3215 0.1783 0.1785 0.3218 0.028 0.867 0.357   0.149         Invertebrata
4 0.3146 0.1853 0.1848 0.3152 0.023 0.676 0.370   0.129         Invertebrata
5 0.2884 0.2117 0.2117 0.2882 0.020 0.445 0.423   0.271         Chondrichthyes
6 0.2943 0.2058 0.2057 0.2942 0.012 0.277 0.412   0.071         Actinopteri

In [60]:
genome_summary <- genome_summary[order(class)]

In [61]:
genome_summary$CG <- round(genome_summary$CG, 3)

In [63]:
genome_summary$CG_OE <- round(genome_summary$CG_OE, 3)
genome_summary$CG_freq <- round(genome_summary$CG_freq, 3)

In [64]:
genome_summary$repeats_ratio <- round(genome_summary$repeats_ratio, 3)

In [66]:
genome_summary$A <- round(genome_summary$A, 3)
genome_summary$C <- round(genome_summary$C, 3)
genome_summary$G <- round(genome_summary$G, 3)
genome_summary$T <- round(genome_summary$T, 3)

In [48]:
head(genome_summary)

  common_name     latin_name                    genome  total_bp   N_chr  A
1 Sea Hare        Aplysia californica           aplCal1  715806041   8767 0.300
2 Lancelet        Cephalochordata               braFlo1  926386587      2 0.294
3 C. intestinalis C. intestinalis               ci3      115227500   1272 0.322
4 S. purpuratus   Strongylocentrotus purpuratus strPur2  907085737 114223 0.315
5 Elephant shark  Callorhinchus milii           calMil1  974498586  21204 0.288
6 Coelacanth      Latimeria chalumnae           latCha1 2860591921  22819 0.294
  C     G     T     CG    CG_OE CG_freq repeats_ratio class
1 0.201 0.201 0.299 0.025 0.627 0.402   0.083         Invertebrata
2 0.206 0.206 0.294 0.028 0.663 0.412   0.063         Invertebrata
3 0.178 0.178 0.322 0.028 0.867 0.357   0.149         Invertebrata
4 0.185 0.185 0.315 0.023 0.676 0.370   0.129         Invertebrata
5 0.212 0.212 0.288 0.020 0.445 0.423   0.271         Chondrichthyes
6 0.206 0.206 0.294 0.012 0.277 0.412   0.071         Actinopteri
  download_link
1 http://hgdownload.soe.ucsc.edu/goldenPath/aplCal1/bigZips/aplCal1.fa.gz
2 http://hgdownload.soe.ucsc.edu/goldenPath/braFlo1/bigZips/braFlo1.fa.gz
3 http://hgdownload.soe.ucsc.edu/goldenPath/ci3/bigZips/ci3.fa.gz
4 http://hgdownload.soe.ucsc.edu/goldenPath/strPur2/bigZips/strPur2.fa.gz
5 http://hgdownload.soe.ucsc.edu/goldenPath/calMil1/bigZips/calMil1.fa.gz
6 http://hgdownload.soe.ucsc.edu/goldenPath/latCha1/bigZips/latCha1.fa.gz

In [4]:
genome_summary[, download_link:= paste0("http://hgdownload.soe.ucsc.edu/goldenPath/", genome, "/bigZips/", genome, ".fa.gz")]

In [12]:
genome_summary[common_name== "Axolotl",download_link:="https://www.axolotl-omics.org/dl/AmexG_v6.0-DD.fa.gz",]

In [39]:
colnames(genome_summary)

 [1] "Common Name"     "Scientific Name" "Genome"          "Total basepairs"
 [5] "N chromosomes"   "A freq."         "C freq."         "G freq."
 [9] "T freq."         "CpG freq."       "CpG obs./exp."   "CG_freq"
[13] "Repeats freq."   "Taxonomic group" "Download link"

In [49]:
colnames(genome_summary)[1] <- "Common Name"

In [50]:
colnames(genome_summary)[2] <- "Scientific Name"

In [51]:
colnames(genome_summary)[3] <- "Genome"

In [52]:
colnames(genome_summary)[6:9] <- paste0(colnames(genome_summary)[6:9], " freq.")

In [53]:
colnames(genome_summary)[4] <- "Total basepairs"

In [54]:
colnames(genome_summary)[5] <- "N chromosomes"

In [55]:
colnames(genome_summary)[10] <- "CpG freq."

In [56]:
colnames(genome_summary)[11] <- "CpG obs./exp."

In [57]:
colnames(genome_summary)[13] <- "Repeats freq."

In [58]:
colnames(genome_summary)[14] <- "Taxonomic group"

In [59]:
colnames(genome_summary)[15] <- "Download link"

In [60]:
genome_summary <- genome_summary[, c(1,2,14, 3:11,13,15)]

In [61]:
head(genome_summary)

  Common Name     Scientific Name               Taxonomic group Genome
1 Sea Hare        Aplysia californica           Invertebrata    aplCal1
2 Lancelet        Cephalochordata               Invertebrata    braFlo1
3 C. intestinalis C. intestinalis               Invertebrata    ci3
4 S. purpuratus   Strongylocentrotus purpuratus Invertebrata    strPur2
5 Elephant shark  Callorhinchus milii           Chondrichthyes  calMil1
6 Coelacanth      Latimeria chalumnae           Actinopteri     latCha1
  Total basepairs N chromosomes A freq. C freq. G freq. T freq. CpG freq.
1  715806041        8767        0.300   0.201   0.201   0.299   0.025
2  926386587           2        0.294   0.206   0.206   0.294   0.028
3  115227500        1272        0.322   0.178   0.178   0.322   0.028
4  907085737      114223        0.315   0.185   0.185   0.315   0.023
5  974498586       21204        0.288   0.212   0.212   0.288   0.020
6 2860591921       22819        0.294   0.206   0.206   0.294   0.012
  CpG obs./exp. Repeats freq.
1 0.627         0.083
2 0.663         0.063
3 0.867         0.149
4 0.676         0.129
5 0.445         0.271
6 0.277         0.071
  Download link
1 http://hgdownload.soe.ucsc.edu/goldenPath/aplCal1/bigZips/aplCal1.fa.gz
2 http://hgdownload.soe.ucsc.edu/goldenPath/braFlo1/bigZips/braFlo1.fa.gz
3 http://hgdownload.soe.ucsc.edu/goldenPath/ci3/bigZips/ci3.fa.gz
4 http://hgdownload.soe.ucsc.edu/goldenPath/strPur2/bigZips/strPur2.fa.gz
5 http://hgdownload.soe.ucsc.edu/goldenPath/calMil1/bigZips/calMil1.fa.gz
6 http://hgdownload.soe.ucsc.edu/goldenPath/latCha1/bigZips/latCha1.fa.gz

In [62]:
my_wt(genome_summary, file.path(analysis_dir, "validation", "genome_stats.tsv"))

In [68]:
file.path(analysis_dir, "validation", "genome_stats.tsv")

[1] "/binfl/lv71484/droman/DNAmeth500species//results_analysis/validation/genome_stats.tsv"